### ISSUE TITLE
How to recompile after adding a custom component

### ISSUE THREAD

**Issue by TheFrankman** [larecipe/larecipe-docs#5]
On my own fork i've created a new component and run `yarn run production`, i would have thought this was all that would be required, however, now the page is fairly broken. I don't believe this to be an issue with the code I have written as it's essentially just 'hello word'

`resources/js/SSTest.vue`

```
<template>
    <div class="icon icon-shape">
        Hello World
    </div>
</template>
<script>
    export default {
        name: "ss-test",
        props: {
        }
    };
</script>
```

`resources/js/plugins/globalComponents.js`

```
...
import LarecipeSwitch from "../components/LarecipeSwitch";
import SSTest from "../components/SSTest"
...

export default {
  install(Vue) {
      ...
      Vue.component(LarecipeSwitch.name, LarecipeSwitch);
      Vue.component(SSTest.name, SSTest)
      ...
```

How do you normally go about re-building after adding new components to the JS ?

**Comment by saleem-hadad** [comment]
Hello 
sorry I didn't catch this issue before
I've changed the internal structure of Larecipe to v2 which is now very easy to add your own plugins and components without having to recompile the entire package, please check that out.
