### ISSUE TITLE
New branch 2.2.0

### ISSUE THREAD

**Issue by WillGoldstein** [larecipe/larecipe-docs#7]
@saleem-hadad my changes to larecipe-docs are done (adjusted the content in two files (authorization.md and configurations.md), but I propose doing a PR into a new branch which doesn't exist yet called 2.2.0 (instead of 2.0 which is technically incorrect). If you agree, I'll wait for you to make that branch for me to PR into. Otherwise, I can PR into 2.0.

This is re [PR 163](https://github.com/saleem-hadad/larecipe/pull/163)

**Comment by saleem-hadad** [comment]
Hi @WillGoldstein ,
Sorry for being late, I created now a new branch 2.2 so you can send PRs
Thanks a lot for your contributions

**Comment by WillGoldstein** [comment]
Awesome thanks @saleem-hadad ! I’ll try to get that up later today. Edit: also, you’re welcome and thanks for the great tool you’ve built!

**Comment by saleem-hadad** [comment]
I think this now can be closed
Thank you again @WillGoldstein 🌹
